import { ApiProperty } from '@nestjs/swagger';

import { Column, Entity, PrimaryColumn } from 'typeorm';
import { Role } from '../enums';
@Entity()
export class User {
  @ApiProperty({
    description: 'custom user id generated by uuid module',
  })
  @PrimaryColumn()
  userId: string;

  @ApiProperty({
    description: 'username of the user',
  })
  @Column()
  userName: string;

  @ApiProperty({
    description: 'business name of user',
  })
  @Column()
  businessName: string;

  @ApiProperty({
    description: 'email of the user',
  })
  @Column()
  email: string;

  @ApiProperty({
    description: 'hashed password',
  })
  @Column()
  password: string;

  @ApiProperty({
    description: 'hashed refresh token',
  })
  @Column({
    nullable: true,
  })
  hashedRt: string;

  @ApiProperty({
    description: 'user verification status',
  })
  @Column({
    default: true,
  })
  isVerified: boolean;

  @ApiProperty({
    description: 'user verification status',
  })
  @Column()
  role: Role;
}
